# Eve Horizon Manifest (v2)
# This file defines your application's deployment configuration
# Learn more: https://github.com/Incept5/eve-horizon

schema: eve/compose/v2
project: eve-starter

# Default values applied across environments
x-eve:
  defaults:
    env: test
    hints:
      harness: mclaude
  requires:
    secrets:
      - name: GITHUB_TOKEN
        description: Required for PR creation and repo access
        remediation: Run `eve secrets set GITHUB_TOKEN <your-token>`

# Environment definitions - where your application runs
environments:
  test:
    type: persistent
  staging:
    type: persistent

# Service definitions - the services that make up your application
services:
  api:
    build:
      context: apps/api
    image: ghcr.io/incept5/eve-starter-api:latest
    ports: [3000]
    environment:
      NODE_ENV: production
    healthcheck:
      path: /health
    x-eve:
      ingress:
        public: true
        port: 3000
      api_spec:
        spec_url: /openapi.json

pipelines:
  ci-cd-main:
    triggers:
      - event: push
        branch: main
    steps:
      - name: integration-tests
        action:
          type: run
          command: ./scripts/integration-test.sh
      - name: deploy-staging
        depends_on: [integration-tests]
        action:
          type: deploy
          environment: staging
