# Eve Horizon Manifest (v2)
# This file defines your application's deployment configuration
# Learn more: https://github.com/Incept5/eve-horizon

schema: eve/compose/v2
project: eve-starter

# Default values applied across environments
x-eve:
  defaults:
    env: test
    hints:
      harness: mclaude
  requires:
    secrets:
      - GHCR_USERNAME
      - GITHUB_TOKEN

registry:
  host: ghcr.io
  namespace: incept5
  auth:
    username_secret: GHCR_USERNAME
    token_secret: GITHUB_TOKEN

# Environment definitions - where your application runs
environments:
  test:
    type: persistent
  staging:
    type: persistent

# Service definitions - the services that make up your application
services:
  api:
    build:
      context: apps/api
    image: ghcr.io/incept5/eve-starter-api:latest
    ports: [3000]
    environment:
      NODE_ENV: production
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
    x-eve:
      ingress:
        public: true
        port: 3000
      api_spec:
        spec_url: /openapi.json

pipelines:
  ci-cd-main:
    trigger:
      github:
        event: push
        branch: main
    steps:
      - name: integration-tests
        script:
          run: ./scripts/integration-test.sh
          timeout: 1800
      - name: release
        depends_on: [integration-tests]
        action:
          type: release
      - name: deploy-staging
        depends_on: [release]
        action:
          type: deploy
          env_name: staging
