# Eve Horizon Manifest (v2)
# This file defines your application's deployment configuration
# Learn more: https://github.com/Incept5/eve-horizon

schema: eve/compose/v1
project: eve-starter

# Default values applied across environments
x-eve:
  defaults:
    env: test
    hints:
      harness: mclaude

# Environment definitions - where your application runs
environments:
  test:
    type: persistent

# Service definitions - the services that make up your application
services:
  api:
    image: ghcr.io/incept5/eve-starter-api:latest
    ports: [3000]
    environment:
      NODE_ENV: production
    healthcheck:
      path: /health
    x-eve:
      ingress:
        public: true
        port: 3000

# Optional: Workflows for CI/CD automation
# workflows:
#   deploy:
#     steps:
#       - name: Build
#         run: docker build -t ghcr.io/incept5/eve-starter-api:$VERSION .
#       - name: Push
#         run: docker push ghcr.io/incept5/eve-starter-api:$VERSION
#       - name: Deploy
#         run: eve env deploy test

# Optional: Pipelines for orchestrating multiple jobs
# pipelines:
#   release:
#     steps:
#       - name: deploy
#         action: { type: deploy }
